name: kfit # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804:gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes

slots:
  # for GtkApplication registration
  kfit:
    interface: dbus
    bus: session
    name: org.kfit.kfit

environment:
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

apps:
  kfit:
    command: desktop-launch $SNAP/share/kfit/kfit.py
    plugs:
      - desktop
      - unity7
      - wayland
      - x11
      - home
      - gsettings
        #    desktop: usr/share/applications/kfit.desktop

parts:

  kfit:
    plugin: python
    python-version: python3
    stage-packages:
      - python3-gi
      - python3-cairo
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - gir1.2-dee-1.0
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-glib-2.0
      - gir1.2-unity-5.0
      - gobject-introspection
      - libgirepository1.0-dev
    source: .
    after: [desktop-gtk3]

  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters:
      - FLAVOR=gtk3
    build-packages:
      - libgtk-3-dev
