name: kfit # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple, graphical spectral fitting in Python # 79 char long summary
description: |
    Simple, graphical spectral fitting in Python

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  kfit:
    command: python3 kfit/application.py
    # command: desktop-launch kfit/application.py
    # plugs: [unity7, home]

parts:
  kfit:
    # See 'snapcraft plugins'
    source: .
    plugin: python
    python-version: python3
    python-packages:
      - pandas
      - numpy
      - matplotlib
      - pyperclip
      - PyQt5
      - lmfit
    stage-packages:
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libavahi-client3
      - libavahi-common3
      - libcairo-gobject2
      - libcups2
      - libepoxy0
      - libgtk-3-0
      - libwayland-cursor0
      - libwayland-egl1
      - libxcomposite1
      - libxcursor1
      - libxinerama1
      - libxrandr2
    after: [qt5]
  qt5:
    source: .
    plugin: nil
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
