name: kfit # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple, graphical spectral fitting with Python and Gtk # 79 char long summary
description: |
  kfit is a tool for quick and easy spectral fitting in science and education.
  It works as a standalone data fitting program for simple tasks, or as an
  exploratory tool in more complex projects. kfit provides a few commonly 
  used peak shapes in engineering and physics, and will eventually support 
  custom models.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804:gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes

apps:
  kfit:
    command: desktop-launch $SNAP/share/kfit/kfit.py
    desktop: kfit.desktop
    plugs:
      - desktop
      - desktop-legacy
      - home
      - unity7
      - wayland
      - x11
      - gsettings

parts:
  kfit:
    plugin: python
    python-version: python3
    stage-packages:
      - python3-gi
      - python3-gi-cairo
    source: .
    after: [desktop-gtk3]
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters:
      - FLAVOR=gtk3
    build-packages:
      - libgtk-3-dev
